/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PremiosRouteImport } from './routes/premios'
import { Route as PrecosRouteImport } from './routes/precos'
import { Route as PostosRouteImport } from './routes/postos'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as BannersRouteImport } from './routes/banners'
import { Route as IndexRouteImport } from './routes/index'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiosRoute = PremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => rootRouteImport,
} as any)
const PrecosRoute = PrecosRouteImport.update({
  id: '/precos',
  path: '/precos',
  getParentRoute: () => rootRouteImport,
} as any)
const PostosRoute = PostosRouteImport.update({
  id: '/postos',
  path: '/postos',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const BannersRoute = BannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/clientes': typeof ClientesRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/postos': typeof PostosRoute
  '/precos': typeof PrecosRoute
  '/premios': typeof PremiosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/clientes': typeof ClientesRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/postos': typeof PostosRoute
  '/precos': typeof PrecosRoute
  '/premios': typeof PremiosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banners': typeof BannersRoute
  '/clientes': typeof ClientesRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/postos': typeof PostosRoute
  '/precos': typeof PrecosRoute
  '/premios': typeof PremiosRoute
  '/servicos': typeof ServicosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banners'
    | '/clientes'
    | '/insights'
    | '/login'
    | '/notificacoes'
    | '/postos'
    | '/precos'
    | '/premios'
    | '/servicos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banners'
    | '/clientes'
    | '/insights'
    | '/login'
    | '/notificacoes'
    | '/postos'
    | '/precos'
    | '/premios'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/banners'
    | '/clientes'
    | '/insights'
    | '/login'
    | '/notificacoes'
    | '/postos'
    | '/precos'
    | '/premios'
    | '/servicos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BannersRoute: typeof BannersRoute
  ClientesRoute: typeof ClientesRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  NotificacoesRoute: typeof NotificacoesRoute
  PostosRoute: typeof PostosRoute
  PrecosRoute: typeof PrecosRoute
  PremiosRoute: typeof PremiosRoute
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premios': {
      id: '/premios'
      path: '/premios'
      fullPath: '/premios'
      preLoaderRoute: typeof PremiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precos': {
      id: '/precos'
      path: '/precos'
      fullPath: '/precos'
      preLoaderRoute: typeof PrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postos': {
      id: '/postos'
      path: '/postos'
      fullPath: '/postos'
      preLoaderRoute: typeof PostosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banners': {
      id: '/banners'
      path: '/banners'
      fullPath: '/banners'
      preLoaderRoute: typeof BannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BannersRoute: BannersRoute,
  ClientesRoute: ClientesRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  NotificacoesRoute: NotificacoesRoute,
  PostosRoute: PostosRoute,
  PrecosRoute: PrecosRoute,
  PremiosRoute: PremiosRoute,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
